# Generated by Django 3.1.7 on 2021-03-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('describe', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
